# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/science-downloader',
                'doc_host': 'https://pfdamasceno.github.io',
                'git_url': 'https://github.com/pfdamasceno/science-downloader',
                'lib_path': 'science_downloader'},
  'syms': {'science_downloader.core': {'science_downloader.core.foo': ('core.html#foo', 'science_downloader/core.py')}}}